import {useEffect,useState} from 'react';
import {AlarmClock,Plus,Volume2,Maximize} from 'lucide-react';
import type {Tracker} from '../lib/tracker';
import {today} from '../lib/tracker';
import {alarmContext} from '../lib/alarm-context';
import {ArcAlarms,alarmNotifications,emptyAlarmState,hasNativeAlarms,syncAlarmContext,type ArcAlarm,type AlarmState} from './native-alarms';
const dayNames=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const fresh=():ArcAlarm=>({id:0,label:'',time:'07:00',days:127,enabled:true,source:'',date:''});
export default function AlarmSettings({state}:{state:Tracker}){
 const[info,setInfo]=useState<AlarmState>(emptyAlarmState),[draft,setDraft]=useState<ArcAlarm|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[ready,setReady]=useState(false);
 const native=hasNativeAlarms(),sources=alarmContext(state),current=today();
 const refresh=async()=>{if(!native){setReady(true);return;}try{await syncAlarmContext(sources);setInfo(await ArcAlarms.getState());setReady(true);}catch(e){setError(e instanceof Error?e.message:'Could not load alarms.');setReady(true);}};
 useEffect(()=>{void refresh();const focus=()=>void refresh();window.addEventListener('focus',focus);return()=>window.removeEventListener('focus',focus);},[]);
 const action=async(fn:()=>Promise<unknown>,message='')=>{setBusy(true);setError('');setStatus('');try{await fn();setInfo(await ArcAlarms.getState());setStatus(message);}catch(e){setError(e instanceof Error?e.message:'Could not update your alarm. Please try again.');}finally{setBusy(false);}};
 const access=(type:'exact'|'notifications'|'fullscreen'|'sound')=>void action(async()=>{if(type==='notifications'){await alarmNotifications();const next=await ArcAlarms.getState();if(!next.notifications)await ArcAlarms.openAccess({type});}else await ArcAlarms.openAccess({type});});
 const save=()=>void action(async()=>{if(!draft)return;if(!draft.label.trim())throw new Error('Give this alarm a name.');if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(draft.time))throw new Error('Choose a valid alarm time.');if(!draft.days)throw new Error('Choose at least one repeat day.');if(draft.source?.startsWith('task:')&&!sources[draft.source]?.dates.includes(draft.date??''))throw new Error('Choose an available date in this task’s week.');if(draft.enabled)await alarmNotifications();await syncAlarmContext(sources);await ArcAlarms.save({alarm:draft});setDraft(null);},'Alarm saved. It will show the task due at that time.');
 const chooseSource=(source:string)=>{if(!draft)return;const src=sources[source],isTask=source.startsWith('task:');setDraft({...draft,source,label:src?.label.slice(0,60)??'',date:isTask?(src.dates.find(d=>d>=current)??src.dates[0]??''):'',days:127});};
 const enabled=info.alarms.filter(a=>a.enabled).length;
 return <section className="android-reminders arc-alarms" aria-labelledby="arc-alarms-title"><div className="reminder-heading"><span className="reminder-icon"><AlarmClock size={22} aria-hidden="true"/></span><div><h3 id="arc-alarms-title">Task alarms</h3><p>The right task. At the right time.</p></div><span className={'reminder-state '+(enabled&&info.exact&&info.notifications?'active':'')}>{enabled?`${enabled} enabled`:'Off'}</span></div>
 <p className="alarm-intro">Rings and vibrates with a full-screen task card. Snooze for 5 minutes or dismiss. Completed habits and tasks are skipped.</p>
 {!native?<p className="reminder-info">Install the updated Android app to set alarms. Your phone controls lock-screen access and alarm volume.</p>:<div className="alarm-access" aria-label="Alarm setup">
 {([['notifications','Notifications',info.notifications],['exact','On-time alarms',info.exact],['fullscreen','Full-screen access',info.fullscreen]] as const).map(([type,label,ok])=><div key={type}><span>{label}<small>{ok?'Allowed':type==='fullscreen'?'Allow to open over the lock screen':'Permission needed'}</small></span><button type="button" disabled={busy||!ready} onClick={()=>access(type)}>{ok?'Settings':'Allow'}</button></div>)}
 <div><span>Alarm volume<small>{info.volume>0?'Uses your phone’s alarm volume':'Muted — turn up alarm volume'}</small></span><button type="button" disabled={busy} onClick={()=>access('sound')}><Volume2 size={17} aria-hidden="true"/> Adjust</button></div>
 </div>}
 {info.next>0&&info.exact&&info.notifications&&<p className="reminder-detail">Next scheduled alarm · {new Date(info.next).toLocaleString('en-IN',{weekday:'short',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'})} · phone time</p>}
 {info.alarms.length>0&&<ul className="alarm-list">{[...info.alarms].sort((a,b)=>a.time.localeCompare(b.time)).map(a=><li key={a.id}><div><strong>{a.time}</strong><span>{sources[a.source??'']?.label??a.label}</span><small>{a.source?.startsWith('habit:')?'Habit’s scheduled days · phone time':a.date?`${a.date} · phone time`:a.days===127?'Every day · phone time':dayNames.filter((_,i)=>a.days&(1<<i)).map(d=>d.slice(0,3)).join(', ')+' · phone time'}{a.source&&!sources[a.source]?.dates.some(d=>d>=current)?' · Nothing remaining':''}</small></div><div className="alarm-list-actions"><label><input type="checkbox" aria-label={'Enable alarm for '+a.label} checked={a.enabled} disabled={busy} onChange={e=>{const enabled=e.target.checked;void action(async()=>{if(enabled)await alarmNotifications();await ArcAlarms.save({alarm:{...a,enabled}});},enabled?'Alarm enabled.':'Alarm paused.');}}/><span>{a.enabled?'On':'Off'}</span></label><button type="button" disabled={busy} onClick={()=>{setDraft({...a});setError('');}}>Edit<span className="sr-only"> {a.label}</span></button></div></li>)}</ul>}
 {!draft?<div className="reminder-buttons"><button type="button" className="reminder-enable" disabled={!native||!ready||busy} onClick={()=>{setDraft(fresh());setError('');setStatus('');}}><Plus size={17} aria-hidden="true"/> Add task alarm</button><button type="button" disabled={!native||!ready||busy} onClick={()=>void action(async()=>{await alarmNotifications();await ArcAlarms.test();},'Test alarm started. Use Dismiss on the alarm screen or notification.')}><Maximize size={16} aria-hidden="true"/> Test ringing</button></div>:<div className="alarm-editor"><h4>{draft.id?'Edit alarm':'New task alarm'}</h4><fieldset disabled={busy}>
 <label>Habit or task<select value={draft.source??''} onChange={e=>chooseSource(e.target.value)}><option value="">Custom alarm</option><optgroup label="Habits">{Object.entries(sources).filter(([k,v])=>k.startsWith('habit:')&&v.dates.some(d=>d>=current)).map(([key,v])=><option key={key} value={key}>{v.label}</option>)}</optgroup><optgroup label="Project & weekly tasks">{Object.entries(sources).filter(([k,v])=>k.startsWith('task:')&&v.dates.some(d=>d>=current)).map(([key,v])=><option key={key} value={key}>{v.label}</option>)}</optgroup></select></label>
 {!draft.source&&<label>Alarm name<input value={draft.label} maxLength={60} onChange={e=>setDraft({...draft,label:e.target.value})} placeholder="e.g. Evening prayer"/></label>}
 <label>Ring at{draft.source?' · phone time':' · phone time'}<input type="time" value={draft.time} onChange={e=>setDraft({...draft,time:e.target.value})}/></label>
 {draft.source?.startsWith('task:')?<label>Task date<input type="date" value={draft.date??''} min={sources[draft.source]?.dates.find(d=>d>=current)} max={sources[draft.source]?.dates.at(-1)} onChange={e=>setDraft({...draft,date:e.target.value})}/></label>:draft.source?<p className="reminder-detail">Follows this habit’s scheduled weekdays during your 90-day arc. Checking it off stops its remaining alarm for that day.</p>:<div className="alarm-days" role="group" aria-label="Repeat days">{dayNames.map((name,i)=><button type="button" key={name} aria-label={name} aria-pressed={!!(draft.days&(1<<i))} onClick={()=>setDraft({...draft,days:draft.days^(1<<i)})}>{name.slice(0,2)}</button>)}</div>}
 </fieldset><div className="reminder-buttons"><button type="button" className="reminder-enable" disabled={busy} onClick={save}>{busy?'Saving…':'Save alarm'}</button><button type="button" disabled={busy} onClick={()=>setDraft(null)}>Cancel</button>{!!draft.id&&<button type="button" disabled={busy} onClick={()=>void action(async()=>{await ArcAlarms.remove({id:draft.id});setDraft(null);},'Alarm deleted.')}>Delete alarm</button>}</div></div>}
 <p className="reminder-detail">Rings for up to 5 minutes. Full-screen access is needed over the lock screen; Android may show a banner while unlocked. Keep alarm volume up and allow alarms in Do Not Disturb. Alarms cannot ring when the phone is off or the app is force-stopped. Dismiss does not mark the task done.</p>
 {status&&<p className="reminder-feedback" role="status">{status}</p>}{error&&<p className="reminder-error" role="alert">{error}</p>}
 </section>;
}
