import {useEffect,useState} from 'react';
import {Bell,Footprints,Droplets} from 'lucide-react';
import {defaultReminders,loadReminderSettings,nativeRemindersAvailable,reminderPermission,reminderSlots,saveReminderSettings,sendTestReminder,type ReminderSettings} from './native-reminders';

export default function AndroidSettings(){
 const[draft,setDraft]=useState<ReminderSettings>({...defaultReminders}),[saved,setSaved]=useState<ReminderSettings>({...defaultReminders}),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[allowed,setAllowed]=useState(false);
 const native=nativeRemindersAvailable(),zone=Intl.DateTimeFormat().resolvedOptions().timeZone;
 useEffect(()=>{let live=true;void Promise.all([loadReminderSettings(),reminderPermission()]).then(([value,permission])=>{if(live){setDraft(value);setSaved(value);setAllowed(permission);setReady(true);}}).catch(e=>{if(live){setReady(true);setError(e instanceof Error?e.message:'Could not load notification settings.');}});const focus=()=>{void reminderPermission().then(setAllowed).catch(()=>setAllowed(false));};window.addEventListener('focus',focus);return()=>{live=false;window.removeEventListener('focus',focus);};},[]);
 const commit=async(enabled:boolean)=>{setBusy(true);setError('');setStatus('');try{const next=await saveReminderSettings({...enabled?draft:saved,enabled},enabled);setSaved(next);setDraft(next);setAllowed(await reminderPermission());setStatus(enabled?'Reminders saved. Your phone will prompt you during these hours.':'Reminders paused. Enable them whenever you are ready.');}catch(e){setError(e instanceof Error?e.message:'Could not save reminders. Please try again.');const actual=await loadReminderSettings();setSaved(actual);if(!enabled)setDraft(actual);}finally{setBusy(false);}};
 const test=async()=>{setBusy(true);setError('');try{await sendTestReminder();setAllowed(true);setStatus('Test reminder sent. Check your notification shade.');}catch(e){setError(e instanceof Error?e.message:'Could not send a test reminder.');}finally{setBusy(false);}};
 let count=0;try{count=reminderSlots(draft).length;}catch{}
 return <section className="android-reminders" aria-labelledby="android-reminders-title"><div className="reminder-heading"><span className="reminder-icon"><Bell size={20}/></span><div><h3 id="android-reminders-title">Gentle desk reminders</h3><p>A quick pause, every 30 minutes.</p></div><span className={'reminder-state '+(saved.enabled&&allowed?'active':'')}>{saved.enabled&&allowed?'On':saved.enabled?'Permission needed':'Off'}</span></div>
 {!native&&<p className="reminder-info">Reminders are available after you install the Android app. This browser preview shows the settings.</p>}
 <fieldset disabled={!ready||busy||!native}><legend className="sr-only">What to remind me about</legend><label className="reminder-option"><Footprints size={19}/><span><strong>Move away from the desk</strong><small>Stand, stretch, or take a short walk.</small></span><input type="checkbox" checked={draft.movement} onChange={e=>setDraft({...draft,movement:e.target.checked})}/></label><label className="reminder-option"><Droplets size={19}/><span><strong>Water check-in</strong><small>A gentle prompt toward your daily goal.</small></span><input type="checkbox" checked={draft.water} onChange={e=>setDraft({...draft,water:e.target.checked})}/></label><div className="reminder-hours"><label>Start<input type="time" value={draft.start} onChange={e=>setDraft({...draft,start:e.target.value})}/></label><label>Finish<input type="time" value={draft.end} onChange={e=>setDraft({...draft,end:e.target.value})}/></label></div></fieldset>
 <p className="reminder-detail">Every day · {count} reminders · {zone}<br/>One combined notification when both are selected. Quiet outside these hours. Android battery settings may delay reminders.</p>
 <div className="reminder-buttons"><button type="button" className="reminder-enable" disabled={!native||!ready||busy} onClick={()=>void commit(true)}>{busy?'Saving…':saved.enabled?'Save reminder settings':'Enable reminders'}</button>{saved.enabled&&<button type="button" disabled={busy} onClick={()=>void commit(false)}>Pause reminders</button>}<button type="button" disabled={!native||!ready||busy} onClick={()=>void test()}>Send test</button></div>
 {status&&<p className="reminder-feedback" role="status">{status}</p>}{error&&<p className="reminder-error" role="alert">{error}</p>}
 </section>;
}
