'use client';

import {personalCommitmentId} from '@/lib/everyday-care';
import {Checkbox} from '@/components/ui/checkbox';
import {Textarea} from '@/components/ui/textarea';
import {dates,formatDate,scheduled,activityDates,ACTIVITY_START,type ActivityKind,type Task,type Tracker} from '@/lib/tracker';

export default function WeeklyCommitment({state,date,week,current,task,onToggle,onPost,onNotes,onActivity,onPersonal}:{onPersonal:(id:string,done:boolean)=>void;state:Tracker;date:string;onActivity:(kind:ActivityKind,done:boolean)=>void;week:number;current:string;task?:Task;onToggle:(done:boolean)=>void;onPost:(date:string,done:boolean)=>void;onNotes:(value:string)=>void}){
 const weekDates=dates(state).slice((week-1)*7,week*7),post=state.habits.find(h=>h.id==='H27');
 const planned=post?weekDates.filter(d=>scheduled(post,d)):[],posted=planned.filter(d=>d<=current&&state.checks[d]?.H27).length;
 const upcoming=weekDates[0]>current;
 return <section className="weekly-commitments" aria-labelledby="commitments-title">
  <div className="commitments-heading"><div><p className="eyebrow">WEEK {String(week).padStart(2,'0')}</p><h2 id="commitments-title">Weekly commitments</h2></div><span>{formatDate(weekDates[0])}–{formatDate(weekDates.at(-1)!)}</span></div>
  <div className="commitment-block movement-block"><div className="movement-heading"><h3>Weekly movement</h3><span>2–3 sessions of each</span></div><p className="muted">Choose any days. These can be part of your workout.</p><div className="movement-options">{([{kind:'cycling',title:'Cycling'},{kind:'other',title:'Running / other activity'}] as const).map(({kind,title})=>{
   const logged=activityDates(state,week,kind,current),done=!!state.activity?.[date]?.[kind],available=date>=ACTIVITY_START&&date<=current;
   return <div className="movement-option" key={kind}><div className="commitment-summary"><h4>{title}</h4><strong aria-label={logged.length+' sessions, target 2 to 3'}>{logged.length}<span> / 2–3</span></strong></div><label className="conversation-check"><Checkbox className="habit-checkbox" checked={available&&done} disabled={!available} aria-label={title+' session on '+formatDate(date,{day:'numeric',month:'short'})} onCheckedChange={v=>onActivity(kind,v===true)}/><span>{done?'Logged':'Log session'} · {formatDate(date,{weekday:'short',day:'numeric',month:'short'})}</span></label><p className="activity-status">{logged.length>=3?'Weekly goal complete':logged.length>=2?'Weekly goal met · third session optional':'Two sessions is the goal; a third is optional.'}</p>{logged.length>0&&<p className="activity-history">Recorded: {logged.map(d=>formatDate(d)).join(', ')}</p>}</div>;
  })}</div><p className="activity-help">Use the date selector to edit another day. Tracking starts 3 Oct.</p></div>
  <div className="commitment-block"><div className="commitment-summary"><h3>LinkedIn posts</h3><strong>{posted}<span> / {planned.length}</span></strong></div><p className="muted">Uses the same checks as your daily routine.</p>{planned.length?<div className="posting-days">{planned.map(d=><label key={d} className="posting-day"><Checkbox className="habit-checkbox" checked={d<=current&&!!state.checks[d]?.H27} disabled={d>current} aria-label={'LinkedIn post on '+formatDate(d,{weekday:'long',day:'numeric',month:'short'})} onCheckedChange={v=>onPost(d,v===true)}/><span>{formatDate(d,{weekday:'short',day:'numeric',month:'short'})}<small>{d>current?'Upcoming':state.checks[d]?.H27?'Published':'Mark after publishing'}</small></span></label>)}</div>:<p className="muted">No LinkedIn posts are scheduled for this week.</p>}</div>
  {task&&<div className="commitment-block"><div className="commitment-summary"><h3>Jarwix conversation</h3><strong>{task.done?1:0}<span> / 1</span></strong></div><label className="conversation-check"><Checkbox className="habit-checkbox" checked={task.done} disabled={upcoming} aria-label="Jarwix customer conversation" onCheckedChange={v=>onToggle(v===true)}/><span>{task.done?'Conversation completed':upcoming?'Opens when this week starts':'One customer conversation, any day this week'}</span></label><details className="commitment-notes"><summary>Notes & outcome{task.notes?.trim()&&<span>Note added</span>}</summary><label className="field note"><span>Customer takeaway & next step</span><Textarea value={task.notes??''} maxLength={5000} placeholder="What did you learn? What happens next?" onChange={e=>onNotes(e.target.value)}/><small className="note-autosave">Saves automatically as you type.</small></label></details></div>}
  <div className="commitment-block personal-week"><div className="movement-heading"><h3>Make room for yourself</h3><span>Any day this week</span></div><div className="personal-week-items">{(['catchup','enjoyment'] as const).map(kind=>{const entry=state.tasks.find(t=>t.id===personalCommitmentId(kind,week));return entry?<label className="personal-week-item" key={entry.id}><Checkbox className="habit-checkbox" checked={entry.done} disabled={upcoming} aria-label={entry.title} onCheckedChange={value=>onPersonal(entry.id,value===true)}/><span><strong>{kind==='catchup'?'One personal catch-up':'Time for enjoyment'}</strong><small>{kind==='catchup'?'A call or meet-up with someone you care about.':'One hour for a hobby, an outing, or just having fun.'}</small></span></label>:null})}</div></div>
 </section>;
}
